import { StyleSheet } from 'react-native';

import { BoxProps } from './types';

export default (props: BoxProps) => {
  const {
    m,
    my,
    mx,
    mt,
    mr,
    mb,
    ml,
    p,
    pt,
    pr,
    pb,
    pl,
    py,
    px,
    bg,
    height,
    width,
    alignItems,
    alignSelf,
    justifyContent,
    flexDirection,
    flex,
    position,
    bottom,
    borderColor,
    borderWidth,
    bbw,
    btw,
    brw,
    blw,
    btrr,
    bbrr,
    btlr,
    bblr,
    r,
    l,
    t,
    b,
  } = props;

  return StyleSheet.create({
    box: {
      ...(m ? { margin: m } : null),
      ...(my ? { marginVertical: my } : null),
      ...(mx ? { marginHorizontal: mx } : null),
      ...(mt ? { marginTop: mt } : null),
      ...(mr ? { marginRight: mr } : null),
      ...(mb ? { marginBottom: mb } : null),
      ...(ml ? { marginLeft: ml } : null),
      ...(p ? { padding: p } : null),
      ...(py ? { paddingVertical: py } : null),
      ...(px ? { paddingHorizontal: px } : null),
      ...(pt ? { paddingTop: pt } : null),
      ...(pr ? { paddingRight: pr } : null),
      ...(pb ? { paddingBottom: pb } : null),
      ...(pl ? { paddingLeft: pl } : null),
      ...(bg ? { backgroundColor: bg } : null),
      ...(flex ? { flex } : null),
      ...(height ? { height } : null),
      ...(width ? { width } : null),
      ...(alignItems ? { alignItems } : null),
      ...(alignSelf ? { alignSelf } : null),
      ...(justifyContent ? { justifyContent } : null),
      ...(flexDirection ? { flexDirection } : null),
      ...(position ? { position } : null),
      ...(typeof bottom !== 'undefined' ? { bottom } : null),
      ...(borderColor ? { borderColor } : null),
      ...(borderWidth ? { borderWidth } : null),
      ...(bbw ? { borderBottomWidth: bbw } : null),
      ...(btw ? { borderTopWidth: btw } : null),
      ...(brw ? { borderRightWidth: brw } : null),
      ...(blw ? { borderLeftWidth: blw } : null),
      ...(btrr ? { borderTopRightRadius: btrr } : null),
      ...(bbrr ? { borderBottomRightRadius: bbrr } : null),
      ...(btlr ? { borderTopLeftRadius: btlr } : null),
      ...(bblr ? { borderBottomLeftRadius: bblr } : null),
      ...(r ? { right: r } : null),
      ...(l ? { left: l } : null),
      ...(t ? { top: t } : null),
      ...(b ? { bottom: b } : null),
    },
  });
};
